### Tek satır for döngüsü (One-liner for)

In [1]:
kelime = "Python"
harf_listesi = []

for harf in kelime:
    harf_listesi.append(harf)
    
print(harf_listesi)

['P', 'y', 't', 'h', 'o', 'n']


In [4]:
harf_listesi = [harf for harf in "Python"]
print(harf_listesi)

['P', 'y', 't', 'h', 'o', 'n']


### Tek satır if (One-liner if)

In [0]:
koşul = True

if koşul:
    kelime = "Elma"
else:
    kelime = "Armut"

In [0]:
kelime = "Elma" if koşul else "Armut"

### Tek satır fonksiyon Lambda (One-liner function Lambda)

In [9]:
kare_al = lambda x: x**2
kare_al(5)

25

### map, reduce, filter, zip fonksiyonları

In [11]:
sayılar = [1, 2, 3, 4, 5, 6, 7]
sayıların_kareleri = []

for sayı in sayılar:
    sayıların_kareleri.append(sayı**2)
print(sayıların_kareleri)

[1, 4, 9, 16, 25, 36, 49]


In [14]:
sayıların_kareleri =  map(kare_al, sayılar)
print(sayıların_kareleri)

for sayı in sayıların_kareleri:
    print(sayı)


1
4
9
16
25
36
49


In [15]:
from functools import reduce

sayılar = [1, 6, 3, 7, 10, 0]
print(reduce(lambda x,y: x if x > y else y, sayılar))

10


In [16]:
def beşten_uzun(kelime):
    if len(kelime) > 5:
        return True
    else:
        return False
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']
uzun_isimler = filter(beşten_uzun, isimler)
print(uzun_isimler)
"""
for isim in uzun_isimler:
    print(isim)
"""

'\nfor isim in uzun_isimler:\n    print(isim)\n'

In [17]:
sayılar = [0, 1, 2, 3, 4, 5]
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']

for i in range(len(sayılar)):
    print(sayılar[i], isimler[i])
    
"""
for i in zip(sayılar, isimler):
    print(i)
"""

0 Oğuz
1 Ahmet
2 Necati
3 Ali
4 Mehmet
5 Ziya


'\nfor i in zip(sayılar, isimler):\n    print(i)\n'

### Assert anahtar kelimesi ( Assert keyword )

In [20]:
yaş = input("Yaşınız:")
assert int(yaş) >= 0, "Yaşınız negatif olamaz"

Yaşınız:90


### Üreteçler (Generators)

In [21]:
def generator():
    i = 1
    print('Öncelikle bu basıldı')
    yield i

    i += 1
    print('Sonra bu')
    yield i

for eleman in generator():
    print("For döngüsü içinde:", eleman)
#print(next())

Öncelikle bu basıldı
For döngüsü içinde: 1
Sonra bu
For döngüsü içinde: 2


In [23]:
a = 5    ## global

def outer(): 
    a = 3  ## local
    def inner():
        nonlocal a  ## nonlocal bir disaridaki degeri cagirir
        a += 5
        print("inner fonksiyon:", a)
    print("outer fonksiyon:", a)
    return inner()

outer()
print("global:", a)

outer fonksiyon: 3
inner fonksiyon: 8
global: 5


### Decorators

In [25]:
from datetime import datetime

def show_time(func):
    def wrapper():
        print("Time:", datetime.now().time())
        func()
    return wrapper

@show_time
def say_hi():
    print("Hi!")

@show_time
def say_bye():
    print("Bye!")
    
say_hi()
say_bye()

Time: 19:02:50.905476
Hi!
Time: 19:02:50.905652
Bye!


# Numpy

![Scalar Vector Matrix Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

In [0]:
import numpy as np

In [28]:
a = np.array([10, 20, 30, 40, 50, 60])   # vector
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(6,)


In [29]:
a[2]

30

In [30]:
a[2] *= 2
print(a[2])

60


In [31]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b)
print(b.shape)
print(b.dtype)

[[10 20 30]
 [40 50 60]]
(2, 3)
int64


In [32]:
a = np.array([10, 20, 30, 40, 50, 60])
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [33]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [34]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [35]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26])

In [36]:
np.max(a)

60

In [37]:
np.min(a)

10

In [57]:
np.argmax(a)  ## max degerin hangi indexte oldugunu gosterir.

5

In [58]:
np.mean(a)

35.0

In [59]:
np.median(a)

35.0

In [60]:
np.std(a)

17.07825127659933

In [62]:
print(b)
# axis=1 => Row
# axis=0 => Column
np.sum(b, axis=1)  # verilen sutun veya satirdaki degerleri topluyor.

[[10 20 30]
 [40 50 60]]


array([ 60, 150])

In [43]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [64]:
full = np.full((3, 3), 5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [46]:
eye = np.eye(5)  # birim matris
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [66]:
arange = np.arange(7)   # 0 dan verilen degere kadar deger olusturur
print(arange)

arange = np.arange(0, 10, 2)  #range'de ondalikli sayilar kullanamiyoruz artis degeri icin
print(arange)

[0 1 2 3 4 5 6]
[0 2 4 6 8]


In [72]:
random = np.random.random((3, 3))  # 0 ve 1 arasinda rastgele sayi uretir
print(random)

random = np.random.random((3, 3)) * 20  # 0 ve 20 arasinda rastgele sayi uretir
print(random)

random = np.ceil(np.random.random((3, 3)) *20 )  # ceil ile ondalikli kismini siliyoruz
print(random)

[[0.52083534 0.47235471 0.15747712]
 [0.6649903  0.02147872 0.91911024]
 [0.02893614 0.64037522 0.65948105]]
[[18.62043317 19.50135349 18.65698415]
 [ 5.30655345 17.70058424 10.8685707 ]
 [ 6.90246365  1.3231496  16.02662891]]
[[ 7. 11. 14.]
 [ 5. 20. 13.]
 [ 3. 13.  9.]]


In [73]:
arr = np.random.randint(20, size=(5, 5))
print(arr)

[[11 19 17 17 10]
 [19 15  4 18  8]
 [ 9 17  1  8  6]
 [11  1  0  9  6]
 [18 15  0 18 14]]


In [74]:
arr[2, 1]

17

In [75]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
eye*6

array([[6., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 6.]])

In [77]:
arr == 4

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [54]:
np.where(arr == 4)

(array([], dtype=int64), array([], dtype=int64))

In [80]:
np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]).reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
c = np.random.randint(10, size=(3, 3))
print(c)
c_inv = np.linalg.inv(c)   
print(c_inv)
# inv : matrisin tersini aliyor
# linalg : linear algebra

[[6 4 7]
 [5 2 8]
 [8 6 9]]
[[ 5.         -1.         -3.        ]
 [-3.16666667  0.33333333  2.16666667]
 [-2.33333333  0.66666667  1.33333333]]


## İç Çarpım (Dot product)
![Dot product](https://algebra1course.files.wordpress.com/2013/02/slide10.jpg)

credit: https://algebra1course.files.wordpress.com/

In [84]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [87]:
b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(b.shape)
print(b)

(2, 3)
[[ 7  8  9]
 [10 11 12]]


In [88]:
axb = np.dot(a, b)

ValueError: ignored

In [92]:
(b.T).shape  #transpozu aliniyor
print(b.T)
print(a)

[[ 7 10]
 [ 8 11]
 [ 9 12]]
[[1 2 3]
 [4 5 6]]


In [93]:
axb = np.dot(a, b.T)
print(axb)
print(axb.shape)

[[ 50  68]
 [122 167]]
(2, 2)
